### ISSUE TITLE
FlashQuality doesn't work

### ISSUE THREAD

**Issue by serialine** [yuyuvn/KanColleViewer#1]
Hi,

Changing flash quality (JavaScript) doesn't work.

I think get iframe (#game_frame) first because of not allowed permission to get inner iframe elements.

`var gameFrame = document.getElementById('game_frame');`
`location.href = gameFrame.src;`

**Comment by yuyuvn** [comment]
Thank you.
ApplyFlashQualityScript method (Grabacr07.KanColleViewer/Views/Controls/KanColleHost.cs) already find iframe which have embed and apply to it.
Will check flash quality function later.

**Comment by yuyuvn** [comment]
It seem work normally in both 3 modes

**Comment by RadarNyan** [comment]
FlashQuality doesn't work for me either.
![kcv](https://cloud.githubusercontent.com/assets/2091529/7448176/e7ffb924-f24d-11e4-982e-34a280f704cb.png)
This is what I got in KCV no matter which mode / quality I choose.
(Reloaded the page, even tried to restart KCV, and KCV is up to date)
![low](https://cloud.githubusercontent.com/assets/2091529/7448202/8e651da4-f24e-11e4-846b-19ddb620e6bc.png)
And this is what the "low" quality really should look like.
The low quality sure looks crappy but it really helps reducing CPU usage.

**Comment by yuyuvn** [comment]
fixed in [v3.7.0r550](https://github.com/yuyuvn/KanColleViewer/releases/tag/v3.7.0r550)
