### ISSUE TITLE
screen freeze

### ISSUE THREAD

**Issue by shiiizuku** [yuyuvn/KanColleViewer#12]
it keeps freezing when im tryin to click the Organize fleet. Then i need to refresh to whole thing before i could play. Its been 15 minutes already but nothing happens. Here's the Printscreen.
![kancolle-150403-10123921](https://cloud.githubusercontent.com/assets/11372944/6976822/68f4cf5a-d9ea-11e4-9b79-89eb2744d654.png)

**Comment by yuyuvn** [comment]
It is kancolle's fault, not KCV's fault. It depend on your network.
If it take too long, you may try clear cache.
