### ISSUE TITLE
Incorrect translations in Quests

### ISSUE THREAD

**Issue by CptBrown** [yuyuvn/KanColleViewer#15]
Sortie! Cruiser Division 18 or 抜錨！「第十八戦隊」, was suppose to be a quest to send Tenryuu, Tatsuta and 2 or more ships to Map 2-3. However, what was shown in your viewer was different. Only after my supposedly completed run for the quest in Map 5-1, I realised that the in-game quest wasn't cleared. Thus, I went to double check with the wiki. Lo and behold, I had went to clear the wrong map with the right composition. I hope that you will change the translations for I do not wish to see any other Admirals to fall to such preposterous ploy.
![image](https://cloud.githubusercontent.com/assets/10834411/7041294/bfb67b94-de0a-11e4-8d70-3c5b8da44f92.png)
![image](https://cloud.githubusercontent.com/assets/10834411/7041341/2a9a877a-de0b-11e4-8130-eb6e23db8540.png)

**Comment by yuyuvn** [comment]
Thank you for your report.
Fixed in 04e8ef43292cbe839902253c6b2382070269349b commit
