### ISSUE TITLE
D10 quest not translated?

### ISSUE THREAD

**Issue by gdp740** [yuyuvn/KanColleViewer#17]
![print](https://cloud.githubusercontent.com/assets/12002920/7213817/8ed0bcee-e5bf-11e4-8b21-36cae3f72cc1.jpg)
![print2](https://cloud.githubusercontent.com/assets/12002920/7213818/8f032f9e-e5bf-11e4-97f7-caa2f80aa5f4.jpg)
![print3](https://cloud.githubusercontent.com/assets/12002920/7213822/c9fddb6c-e5bf-11e4-9dad-0a52647b5d3e.jpg)

**Comment by yuyuvn** [comment]
Thank you for your report.

**Comment by gdp740** [comment]
Thanks for the update, glad to help :)
