### ISSUE TITLE
Overwiew/Fleet tab

### ISSUE THREAD

**Issue by shiiizuku** [yuyuvn/KanColleViewer#21]
it doens't show any fllet name,ships in the Fleet tab
![untitled](https://cloud.githubusercontent.com/assets/11372944/7406928/373c32a2-ef46-11e4-9252-cadd61275587.png)

**Comment by yuyuvn** [comment]
try restart KCV

**Comment by shiiizuku** [comment]
i already did that,still the same

**Comment by shiiizuku** [comment]
woops, its already fixed. Thanks mate
