### ISSUE TITLE
UI Enhancement by coloring the border

### ISSUE THREAD

**Issue by Astra-RX** [yuyuvn/KanColleViewer#24]
I've used a plugin that using the KCV border color to indicate fleet condition. It uses original blue for normal, orange for battle, it adds an important red border to indicate heavily broken girl in fleet. I think it is very clever. This will prevent ship sink definitely.

Another way is adding more color to fleet indicator for resupply, critical damaged, bad condition separately, not using one color for all of them.

**Comment by yuyuvn** [comment]
I won't add more color unless Grabacr07 add more color. I think fewer color make it easy to remember which color is which state. 
btw, feel free to make or use plugin to do that featrure if you want

**Comment by kagoromo** [comment]
In my opinion, the border color should be blue for any non-combat screen, green for during sorties and orange for when there is a critically damaged ship (the border should stay orange until there is no more critically damaged ship in any fleet, no matter during sorties or not). It would be more intuitive that way; the border color will then match the background of the info text on top of the ships as well (that text is "Ready for sortie!" in this snapshot: http://puu.sh/hSTIL/ee8ae816b9.png)
