### ISSUE TITLE
new version UI display bug?

### ISSUE THREAD

**Issue by Justforpotm** [yuyuvn/KanColleViewer#26]
I just downloaded the newest version and felt strange when playing-.-
Had to pull out some old screen shots and found this.

Old version:
![image](https://cloud.githubusercontent.com/assets/12291507/7510582/7f107e56-f452-11e4-84fa-462d4565834d.png)

New version 3.7.0r544
![image](https://cloud.githubusercontent.com/assets/12291507/7510908/bc9940ac-f455-11e4-85ef-bc203a6dd484.png)

Also download the original version 3.7:
![image](https://cloud.githubusercontent.com/assets/12291507/7510960/2da06082-f456-11e4-9102-1454dc048b7a.png)

I don't know if the new version is meant to be like this.
Try to fix it by changing the settings but failed -.-

**Comment by yuyuvn** [comment]
it's function, not bug :trollface: 
I just change background color to make layout not seem unconnected
