### ISSUE TITLE
Incorrect Log Info

### ISSUE THREAD

**Issue by gdp740** [yuyuvn/KanColleViewer#27]
Drops from E4 under "Operation" Column is displayed as E2 instead

**Comment by yuyuvn** [comment]
Both E2 and E4 have the same name (カレー洋リランカ島沖)...

**Comment by gdp740** [comment]
well, thou i meant this column that shows "World E?" as drops from E4 is displayed as E2 like the one in the pic

![print](https://cloud.githubusercontent.com/assets/12002920/7550298/83e64f44-f68e-11e4-9688-34f08b659ab3.jpg)
