### ISSUE TITLE
Suggestion: Screenshot button ~ exit accidents

### ISSUE THREAD

**Issue by gdp740** [yuyuvn/KanColleViewer#28]
accidentally closing the viewer when one wants to take a screenshot. 
It may be a rare occurrence but  the distance between the close and screenshot buttons are somewhat small which allows such possibility to exist.

well, such thing happened to me twice, and happened to witness someone did the same thing recently.

I think the location of the un/mute button is safe enough and at the same time it is less used compared to the screenshot button, how about interchanging their positions?

or maybe adding an additional prompt for close button? (which can also prevent accidental closure when closing equipment/ship list window)
~ ~
p.s. not sure if posted at right place, but I just want to voice out some thoughts from me and fellow KC players of a certain group

**Comment by yuyuvn** [comment]
added in [v3.7.0r550](https://github.com/yuyuvn/KanColleViewer/releases/tag/v3.7.0r550)
