### ISSUE TITLE
Mid-sortie packets update

### ISSUE THREAD

**Issue by gdp740** [yuyuvn/KanColleViewer#33]
![print](https://cloud.githubusercontent.com/assets/12002920/7678577/d844f036-fd87-11e4-991b-1237f7f80b9e.jpg)

you might have noticed alr, but i`ll it here just in case

halfway of 1-1 alr but no updates on morale(started run with 61 morale)
nor ammo/fuel nor hp

**Comment by yuyuvn** [comment]
fixed in the last release
