### ISSUE TITLE
Not Responding

### ISSUE THREAD

**Issue by ghost** [yuyuvn/KanColleViewer#34]
Seems the newest version likes to hang up between screens. During missions it will often freeze for several seconds and show 'Not responding' after the compass spin or while loading the combat screen after choosing formation.

**Comment by mikenzb** [comment]
Have you checked your adobe flash settings? Since the newer version reset your settings.. I recommending best flash quality... and direct flash window, I remember the other settings seem to make my game lag as well.....

**Comment by ghost** [comment]
Well it seems that thid may be a computer issue. My hard drive just
crashed. I think it ded. Sorry for the alarm this is likely just me lol
