### ISSUE TITLE
Choose what items to track

### ISSUE THREAD

**Issue by ninexball** [yuyuvn/KanColleViewer#36]
Hi, I was wondering if it would be possible to change the item counts to track from Instant Builds (Flamethrowers) to Repair Buckets.  I know that instant builds aren't shown on main screen, but I don't usually care about their numbers as much as buckets.

Thanks

**Comment by mikenzb** [comment]
I would like to add on to this, Should replace the remodel kits number (screws for akashi) to buckets above the flamethrowers. 

I know Yuubari's Fork also does that so I imagine it can't be to hard to do.

**Comment by yuyuvn** [comment]
buckets already show in game screen so It isn't nessesally to show in kcv

**Comment by ninexball** [comment]
Yes, it is a matter of preference.  Originally bucket counts were not shown on main screen.  That information isn't available while on sortie, but is often more useful to know.  I know a lot of people switching over from other forks are used to it being tracked in KCV, so they don't really need to pay as much attention and track their bucket count in their mind.

**Comment by yuyuvn** [comment]
The purpose of KCV is to provide easy access to extra information not readily available in the game screen, not taking user's attention from the game. Since bucket numbers have already been displayed inside the game, you should get used to finding it there instead of the viewer.
