### ISSUE TITLE
Game doesn't load

### ISSUE THREAD

**Issue by MirrorCubeSquare** [yuyuvn/KanColleViewer#38]
After the web page loaded,the program starts to put the flash screen to the mid
but after that, the screen becomes black out(that black loading screen with a white ship)
Version :after 3.7.0r550 to 3.8.1r552
# OS : win 7

P.S though the screen is blacked out , i can still hear the background sound

**Comment by wyjtm** [comment]
I also have this problem

**Comment by yuyuvn** [comment]
try clear your cache

**Comment by wyjtm** [comment]
clear cache invalid

**Comment by wyjtm** [comment]
I removed the following code Problem disappears  But flash rendering invalid

for (var objs = document.embeds, i = objs.length - 1; i &gt;= 0; i--) {{

```
    var embedElem = document.createElement('embed');
    var parentElem = objs[i].parentNode;
    embedElem.setAttribute('quality', '{0}');
    embedElem.setAttribute('wmode', '{1}');
    embedElem.setAttribute('type', 'application/x-shockwave-flash');
    embedElem.setAttribute('id', objs[i].getAttribute('id'));
    embedElem.setAttribute('width', objs[i].getAttribute('width'));
    embedElem.setAttribute('height', objs[i].getAttribute('height'));
    embedElem.setAttribute('src', objs[i].getAttribute('src'));
    embedElem.setAttribute('bgcolor', objs[i].getAttribute('bgcolor'));
    embedElem.setAttribute('allowScriptAccess', objs[i].getAttribute('allowScriptAccess'));
    embedElem.setAttribute('base', objs[i].getAttribute('base'));
    parentElem.removeChild(objs[i]);
    parentElem.appendChild(embedElem);
}}

for (objs = document.getElementsByTagName('object'), i = objs.length - 1; i &gt;= 0; i--) {{
    var embedElem = document.createElement('embed');
    var parentElem = objs[i].parentNode;
    embedElem.setAttribute('quality', '{0}');
    embedElem.setAttribute('wmode', '{1}');
    embedElem.setAttribute('id', objs[i].getAttribute('id'));
    embedElem.setAttribute('type', 'application/x-shockwave-flash'); 
    embedElem.setAttribute('width', objs[i].getAttribute('width'));
    embedElem.setAttribute('height', objs[i].getAttribute('height'));       

    for (var c = objs[i].childNodes, j = c.length - 1, set = false; j &gt;= 0; j--) {{
        if ((c[j].tagName == 'PARAM') &amp;&amp; (c[j].getAttribute('name').toLowerCase() == 'src'))
            embedElem.setAttribute('src', c[j].getAttribute('value'));
        else if ((c[j].tagName == 'PARAM') &amp;&amp; (c[j].getAttribute('name').toLowerCase() == 'movie'))
            embedElem.setAttribute('src', c[j].getAttribute('value'));
        else if ((c[j].tagName == 'PARAM') &amp;&amp; (c[j].getAttribute('name').toLowerCase() == 'bgcolor'))
            embedElem.setAttribute('bgcolor', c[j].getAttribute('value'));
        else if ((c[j].tagName == 'PARAM') &amp;&amp; (c[j].getAttribute('name').toLowerCase() == 'allowscriptaccess'))
            embedElem.setAttribute('allowScriptAccess', c[j].getAttribute('value'));
        else if ((c[j].tagName == 'PARAM') &amp;&amp; (c[j].getAttribute('name').toLowerCase() == 'base'))
            embedElem.setAttribute('base', c[j].getAttribute('value'));
    }}

    parentElem.removeChild(objs[i]);
    parentElem.appendChild(embedElem);
```

**Comment by yuyuvn** [comment]
Change the flash quality setting:
Flash window to Direct

**Comment by wyjtm** [comment]
Flash window to Direct  
Invalid way

> Normally enter the game
> KanColleViewer Extraction Flash Screen
> turn into loading screen（Black screen and White boat）

**Comment by iyomumx** [comment]
Add a placeholder before removeChild like

```
parentElem.appendChild(document.createTextNode("just a placeholder");
parentElem.removeChild(objs[i]);
parentElem.appendChild(embedElem);
```

fixed for me

**Comment by MitsuhaMiyamizu** [comment]
I have this problem,too
At first I thought the problem lies in the cache,so I did thorough clean to get all cookie and cache removed.It works for a short while,but when I tried again,this problem showed again.I really suspect that there seems to be existing a problem where the framework handle the flash,maybe the flash quality customization is the key.I don't know,so I get back to use Grabacr07's version.It won't crash like the situation above.Could you please check the plugin again,I hope it can help you to troubleshoot the issues,thanks very much!

**Comment by MirrorCubeSquare** [comment]
> Change the flash quality setting:
> Flash window to Direct
> though this works for me, but i believe there are problems lie in the process of rendering flash
> Other KCV-like browser using same technique for quality changing haven't reported same issue
> like a alter edition of 74EO
> repo:
> https://github.com/tsanie/ElectronicObserver/tree/makai

**Comment by MitsuhaMiyamizu** [comment]
I tried,but it still happened.I have to come back to Grabacr07's version

**Comment by asahinobori** [comment]
I have this problem, too.
And I use token link to get rid of the problem

**Comment by jtyuan** [comment]
It happened to me too. My temporary solution is ctrl+wheel down and right click blank area to refresh the page (it wont try to switch to adapted window again), and I can play the game normally. (But the scrollbars wont disappear...)

**Comment by YusaKatsuragi** [comment]
i have this problem as well, i need to refresh it couple times to make it work :/

**Comment by yuyuvn** [comment]
Try update your flash player to lastest version
If not work, edit file KanColleViewer.exe.config:
change

```
<value>var flashQuality = function () {{
```

to

```
<value>var flashQuality = function () {{ return;
```

**Comment by wyjtm** [comment]
<value>var flashQuality = function () {{
to
<value>var flashQuality = function () {{ return;

After the change KCV can work normal
But.............
Flash setting function fails...............................

**Comment by MitsuhaMiyamizu** [comment]
please do not close the issue until it is really solved,thanks.
the really efficient way is add the below line of

parentElem.appendChild(document.createTextNode("just a placeholder");

in front of the second line of:

parentElem.removeChild(objs[i]);

the result seems to be like this:

else if ((c[j].tagName == 'PARAM') &amp;&amp; (c[j].getAttribute('name').toLowerCase() == 'base'))
embedElem.setAttribute('base', c[j].getAttribute('value'));
}}

parentElem.appendChild(document.createTextNode("just a placeholder");
parentElem.removeChild(objs[i]);
parentElem.appendChild(embedElem);
}}
}};

(All the alternation need change the configuration file "KanColleViewer.exe.config")
Could you please do not close the problem until it is really solved?That's not the right way to cope with the issue,I think.No offense,this attitude is not helpful enough to solve the problem.

**Comment by yuyuvn** [comment]
@Kiritoalex I didn't close this issue, just close the dupplication one

**Comment by MitsuhaMiyamizu** [comment]
OK,I know,sorry for what I said,XDDDD

**Comment by wyjtm** [comment]
@Kiritoalex 

After modifying KCV not start

---

<value>var flashQuality = function () {{
to

<value>var flashQuality = function () {{ return;

This method can be normal operation and use KVC

But   Flash render settings complete failure can not be used

**Comment by yuyuvn** [comment]
try replace

```
    flashQuality();
    clearInterval(TimedInject);
```

to

```
    clearInterval(TimedInject);
    flashQuality();
```

**Comment by wyjtm** [comment]
@yuyuvn 

After the change
Flash rendering still can not be used

**Comment by yuyuvn** [comment]
If don't change anything, do flash setting mode work?

**Comment by wyjtm** [comment]
If don't change anything,
game adaptive window After
KCV windows will become  Black screen + white boat

**Comment by yuyuvn** [comment]
please upload screen shot of white boat with flash quality setting low and flash quality setting best (default KanColleViewer.exe.config)

**Comment by wyjtm** [comment]
![high](https://cloud.githubusercontent.com/assets/10809623/7761682/637efc8e-005b-11e5-8c9f-053a6583ceec.png)

![low](https://cloud.githubusercontent.com/assets/10809623/7761685/738dd01e-005b-11e5-87ae-c59565d5cda4.png)

They are adaptive window after

P.S....
Before that has entered the game
Or enter the game start screen

Screenshot of Black Ships

**Comment by yuyuvn** [comment]
replace function flashQuality to:

```
  var flashQuality = function () {{
  for (var objs = document.embeds, i = objs.length - 1; i &gt;= 0; i--) {{

    var embedElem = document.createElement('embed');
    var parentElem = objs[i].parentNode;
    embedElem.setAttribute('quality', '{0}');
    embedElem.setAttribute('wmode', '{1}');
    embedElem.setAttribute('src', objs[i].getAttribute('src'));
    embedElem.setAttribute('base', objs[i].getAttribute('base'));
    embedElem.setAttribute('type', 'application/x-shockwave-flash');
    embedElem.setAttribute('id', objs[i].getAttribute('id'));
    embedElem.setAttribute('width', objs[i].getAttribute('width'));
    embedElem.setAttribute('height', objs[i].getAttribute('height'));
    embedElem.setAttribute('bgcolor', objs[i].getAttribute('bgcolor'));
    embedElem.setAttribute('allowScriptAccess', objs[i].getAttribute('allowScriptAccess'));
    parentElem.removeChild(objs[i]);
    parentElem.appendChild(embedElem);
}}

for (objs = document.getElementsByTagName('object'), i = objs.length - 1; i &gt;= 0; i--) {{
    var embedElem = document.createElement('embed');
    var parentElem = objs[i].parentNode;
    embedElem.setAttribute('quality', '{0}');
    embedElem.setAttribute('wmode', '{1}');
    embedElem.setAttribute('id', objs[i].getAttribute('id'));
    embedElem.setAttribute('type', 'application/x-shockwave-flash'); 
    embedElem.setAttribute('width', objs[i].getAttribute('width'));
    embedElem.setAttribute('height', objs[i].getAttribute('height'));

    for (var c = objs[i].childNodes, j = c.length - 1, set = false; j &gt;= 0; j--) {{
        if ((c[j].tagName == 'PARAM') &amp;&amp; (c[j].getAttribute('name').toLowerCase() == 'src'))
            embedElem.setAttribute('src', c[j].getAttribute('value'));
        else if ((c[j].tagName == 'PARAM') &amp;&amp; (c[j].getAttribute('name').toLowerCase() == 'base'))
            embedElem.setAttribute('base', c[j].getAttribute('value'));
        else if ((c[j].tagName == 'PARAM') &amp;&amp; (c[j].getAttribute('name').toLowerCase() == 'movie'))
            embedElem.setAttribute('src', c[j].getAttribute('value'));
        else if ((c[j].tagName == 'PARAM') &amp;&amp; (c[j].getAttribute('name').toLowerCase() == 'bgcolor'))
            embedElem.setAttribute('bgcolor', c[j].getAttribute('value'));
        else if ((c[j].tagName == 'PARAM') &amp;&amp; (c[j].getAttribute('name').toLowerCase() == 'allowscriptaccess'))
            embedElem.setAttribute('allowScriptAccess', c[j].getAttribute('value'));
    }}

    parentElem.removeChild(objs[i]);
    parentElem.appendChild(embedElem);
}}
```

}};

**Comment by wyjtm** [comment]
Not work
With no difference before replacement

**Comment by MitsuhaMiyamizu** [comment]
![2015-05-22_142042](https://cloud.githubusercontent.com/assets/9009218/7765206/d1b889ea-008d-11e5-8ad4-4e520c2626b2.png)
Just modify this file like this,you may have misunderstood what we have recommended.

**Comment by yuyuvn** [comment]
@Kiritoalex 
Your code missing a ")" character, it will occur error.

---

Another test: (each time I said try replace, please replace from default KanColleViewer.exe.config)
try replace

```
if (document.getElementById('flashWrap').innerHTML.length &gt; 10) {{
```

to

```
if (document.getElementById('flashWrap').innerHTML.length &gt; 300) {{
```

**Comment by c933103** [comment]
See t.cn/R24qcXA , multiple report of initially not working but ok after applying iyomumx's fix.

**Comment by wyjtm** [comment]
if (document.getElementById('flashWrap').innerHTML.length &gt; 10) {{
to

if (document.getElementById('flashWrap').innerHTML.length &gt; 300) {{

not work

**Comment by yuyuvn** [comment]
replace

```
CheckChange();
```

to

```
if (document.readyState == 'interactive' || document.readyState == 'complete')
    CheckChange();
```

**Comment by wyjtm** [comment]
CheckChange();
to

if (document.readyState == 'interactive' || document.readyState == 'complete')
    CheckChange();

not work....

**Comment by yuyuvn** [comment]
change all value of FlashQualityJS to

```
function kcsFlash_StartFlash(worldServerAddr)
{{
    // Flash パラメータを設定する。
    var flashParams =
    {{
        "id"                : "externalswf",
        "width"             : "800",
        "height"            : "480",
        "wmode"             : "{1}",
        "quality"           : "{0}",
        "bgcolor"           : "#000000",
        "allowScriptAccess" : "always"
    }};

    // Flash の貼り付けに失敗した場合のメッセージを設定する。
    document.getElementById("flashWrap").innerHTML = ConstMessageInfo.InstallFlashMessage;

    // Flash をページに貼り付ける。
    gadgets.flash.embedFlash(
        worldServerAddr + ConstURLInfo.MainFlashURL + "?api_token=" + flashInfo.apiToken + 
                                  "&amp;api_starttime=" + flashInfo.apiStartTime,
        document.getElementById("flashWrap"),
        6,
        flashParams
    );

    // サンクスページ用フラッシュのエリアの高さを変更する。
    document.getElementById("adFlashWrap").style.height = "0px";

    // ワールド選択用フラッシュのエリアの高さを変更する。
    document.getElementById("wsFlashWrap").style.height = "0px";

    // ゲーム用フラッシュのエリアのエリアの高さを変更する。
    document.getElementById("flashWrap").style.height = "480px";

    // ガジェットの高さを調整する。
    gadgets.window.adjustHeight(ConstGadgetInfo.height);
}}
```

**Comment by iyomumx** [comment]
change all value of FlashQualityJS **works**, thx

**Comment by yuyuvn** [comment]
Fixed in the latest version

**Comment by wyjtm** [comment]
problem solving
thx
