### ISSUE TITLE
Fleet Info doesn't update in the middle of sorties.

### ISSUE THREAD

**Issue by EcclairS** [yuyuvn/KanColleViewer#39]
As the title says, the Fleet info does update when the sortie ended but doesn't when in the middle of a sortie. _Edit_ this is the 2nd node of 3-5 btw.

![fleetstatus](https://cloud.githubusercontent.com/assets/12514389/7705811/1712de58-fe79-11e4-8ee4-13e237cc38fa.png)

**Comment by yuyuvn** [comment]
dupplication https://github.com/yuyuvn/KanColleViewer/issues/33
