### ISSUE TITLE
Hey,here is a Chinese version of those xml-Files in the Translations Folder

### ISSUE THREAD

**Issue by AnnaKutou** [yuyuvn/KanColleViewer#4]
I tried to translate them with my friend and we made it. But I am not good at programming and don't know how to use Github. So I had to come here and hope you can consider helping me let these files be released.
Then, here is the link: http://1drv.ms/1D9WDa3

**Comment by yuyuvn** [comment]
Thank you for your translate.
Unfortunately, my fork no longer support multi language for translation xml files. You can create a new repository which have Version.xml & translations. Make it a [github page](https://pages.github.com/) then contact Yuubari to join https://github.com/KCV-Localisation

**Comment by AnnaKutou** [comment]
All right. Thank you all the same.^_^
