### ISSUE TITLE
Game doesn't load

### ISSUE THREAD

**Issue by Athrawne** [yuyuvn/KanColleViewer#41]
When I switched to the newer release, which I think is 3.8.1 r552, my game failed to load. It would remain stuck on the bouncing boat screen. I managed to get it to work maybe 2/5 times. When I switched back to the older version I was using which was 3.7.0 r543, it worked fine.

**Comment by jtyuan** [comment]
same issue for me. it happens when KCV try to auto-fit the flash window

**Comment by yuyuvn** [comment]
dupplication
https://github.com/yuyuvn/KanColleViewer/issues/38
