### ISSUE TITLE
How to directly go into the api instead of DMM site?

### ISSUE THREAD

**Issue by ogorhan** [yuyuvn/KanColleViewer#47]
So after upgrading to the latest version, instead of directly opening the game through the api link it goes to the DMM website for kancolle. So I have to copy and paste my api link into the search bar manually which wasnt the case for the previous version. I always just copied and pasted my api link into the config file when upgrading and it never was a issue.

How do I fix this?

**Comment by yuyuvn** [comment]
I alway use api link to play Kancolle and don't get any error.

**Comment by yuyuvn** [comment]
KanColleUrl setting is at bottom of KanColleViewer.exe.config file
