### ISSUE TITLE
Form the new Destroyer Division 6! quest description

### ISSUE THREAD

**Issue by gdp740** [yuyuvn/KanColleViewer#49]
I think its supposed to be Akatsuki kai ni as Flagship, 

![print](https://cloud.githubusercontent.com/assets/12002920/7883109/925f7bbe-0646-11e5-97cb-636bf55a0ade.jpg)
![print2](https://cloud.githubusercontent.com/assets/12002920/7883111/934c687a-0646-11e5-9ed1-5f9308606cd6.jpg)
![print3](https://cloud.githubusercontent.com/assets/12002920/7883112/943ff6f2-0646-11e5-85b8-6985c1974ad8.jpg)

**Comment by c933103** [comment]
yes it is. btw, please fix the capitalization for Hibiki.

Edit: btw, can someone test could Вер replace Hibiki?

**Comment by yuyuvn** [comment]
according to wikiwiki, you can use Bep instead of Hibiki
