### ISSUE TITLE
Traditional Chinese language support.

### ISSUE THREAD

**Issue by c933103** [yuyuvn/KanColleViewer#54]
As per an issue on Grabacr's KCV https://github.com/Grabacr07/KanColleViewer/pull/87 , it is found that the the traditional chinese interface document were completely translated on transifex as seen in https://www.transifex.com/projects/p/kancolleviewer/ but have never been made available in KCV's language menu. Could this fork implement traditional chinese interface selection directly? (From what i read there're also Norwegian translation being completed)

**Comment by yuyuvn** [comment]
Grabacr's KCV have very small number of localizable strings (he usually use fixed string). Compeletely translated resource in his project is just 29% compare to my fork.
btw, I have created transifex project here: https://www.transifex.com/projects/p/kancolleviewer-1/

**Comment by c933103** [comment]
pressed the 'join team' button, waiting for approval.

**Comment by yuyuvn** [comment]
Accepted, thank you.

**Comment by c933103** [comment]
Where do the #253 string in resources.resx appear?

**Comment by yuyuvn** [comment]
It appear here:
Tooltip for save filter options.
![ss](https://cloud.githubusercontent.com/assets/6410496/8027558/95b41854-0dc3-11e5-9de8-efe654931958.jpg)

**Comment by c933103** [comment]
Thx.

**Comment by c933103** [comment]
and all strings translated
