### ISSUE TITLE
Cannot open KanColleViewer.exe

### ISSUE THREAD

**Issue by baubau09** [yuyuvn/KanColleViewer#71]
KCV Version 3.8.2 rev 557
Try to open it many times but there's nothing happen
My OS is Win 8 SL
This is the errorlog: http://pastebin.com/ZCh370bi

**Comment by EnderShadow** [comment]
I'm having the same problem

**Comment by NeilAlpha** [comment]
windows 10，the same problem

**Comment by gakada** [comment]
Same on 8.1 for me (with the same error.log about Linq), though I can play from https://github.com/yuyuvn/KanColleViewer/commit/2584c2581532cd8e5feec216e8ba7907fa61292f in VS.

**Comment by yuyuvn** [comment]
Uploaded new rebuild, sorry you guy.

**Comment by yuyuvn** [comment]
Uploaded rebuiled, sorry you guy
