### ISSUE TITLE
Question with LogViewer and .csv files

### ISSUE THREAD

**Issue by d956381604** [yuyuvn/KanColleViewer#72]
I accidentally opened the .csv files with microsoft excel. And now the LogViewer stop to record any of those logs now. I tried to download a KCV but it didn't work. What should I do to fix that?

**Comment by gakada** [comment]
You mean while they're opened in Excel or even after you closed them?

If they're not locked by Excel, then Logger will add new entries (you can check `KanColleViewer*/Logs/*.csv` with any text editor) and LogViewer will display things properly (unless Excel somehow messed up the format, check the files, or move them out of Logs directory).

**Comment by d956381604** [comment]
I'd believe that Excel somehow messed up the whole setting for .csv files. I tried to move them out of the Logs folder, and it won't even create new .csv files any more. And I'm not quite sure how to check if they are locked by Excel.

**Comment by gakada** [comment]
Should't be locked if you can move/delete them.

So, no BuildItemLog.csv or BuildShipLog.csv when you build item or ship? Even if you delete/backup the whole thing and download and extract KCV into some other folder?

**Comment by d956381604** [comment]
Nope, it didn't work. But the strange thing is that it still won't fix even after I uninstalled Excel from my computer.

**Comment by gakada** [comment]
Well, maybe it's not Excel then, the Logger and LogViewer both are quite simple, they just write and read files, I don't know what can possibly go wrong here.

Maybe see https://github.com/KCV-Localisation/KanColleViewer/blob/master/FAQ.md, if permissions are right, you can also try to delete `%APPDATA%\grabacr.net\` folder, start KCV from its directory and check the settings, including Logging checkbox in Settings -> Other (it's disabled by default).

**Comment by d956381604** [comment]
Yeah, deleting that folder is right! No wonder why it always remembers my proxy server. Thank you! :)
